"""zemax_export.py – Export a ThickPrescription to Zemax .zmx sequential format.

Generates a minimal but valid .zmx file that can be opened in Zemax OpticStudio.
Only standard surfaces (STANDARD) with refractive index / Abbe number are used;
full Sellmeier dispersion data is not embedded (Zemax will use its own catalog
or the user can re-assign glasses).
"""

from __future__ import annotations

from .models import Candidate, Inputs, ThickPrescription


def export_zmx(
    rx: ThickPrescription,
    cand: Candidate,
    inputs: Inputs,
    filepath: str,
) -> None:
    """Write a Zemax-compatible .zmx file for the given prescription."""
    lines: list[str] = []

    # Header
    lines.append("VERS 140122 200 36")
    lines.append("MODE SEQ")
    lines.append(f"NAME {cand.glass1}+{cand.glass2}")
    lines.append("NOTE 0 0")
    lines.append(f"NOTE 0 Generated by AutoAchromat")
    lines.append("")

    # Unit: mm
    lines.append("UNIT MM X W X CM MR CPMM")
    lines.append("")

    # Wavelengths (µm → µm, Zemax uses µm)
    lam0, lam1, lam2 = inputs.lam0, inputs.lam1, inputs.lam2
    lines.append(f"WAVM 1 {lam1} 1")
    lines.append(f"WAVM 2 {lam0} 1")
    lines.append(f"WAVM 3 {lam2} 1")
    lines.append(f"PWAV 2")  # primary wavelength = lam0
    lines.append("")

    # Entrance pupil
    lines.append(f"ENPD {inputs.D}")
    lines.append("")

    # Field
    lines.append("FTYP 0 0 1 1 0 0 0")  # object angle
    lines.append(f"FLDN 1 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0")
    lines.append(f"FLDN 2 {inputs.half_field_angle} 0.0 1.0 0.0 0.0 0.0 0.0 0.0")
    lines.append("")

    # Surfaces
    e1, e2 = rx.elements

    # Surface 0: Object (infinity)
    lines.append("SURF 0")
    lines.append("  TYPE STANDARD")
    lines.append("  CURV 0.0")
    lines.append("  DISZ Infinity")
    lines.append("")

    # Surface 1: Stop (first lens surface)
    lines.append("SURF 1")
    lines.append("  TYPE STANDARD")
    lines.append("  STOP")
    lines.append(f"  CURV {1.0 / e1.R_front if abs(e1.R_front) > 1e-12 else 0.0}")
    lines.append(f"  DISZ {e1.t_center}")
    lines.append(f"  GLAS {cand.glass1} 0 0 {e1.nd} {e1.vd}")
    lines.append("")

    if rx.system_type == "cemented":
        # Surface 2: cemented interface
        lines.append("SURF 2")
        lines.append("  TYPE STANDARD")
        lines.append(f"  CURV {1.0 / e1.R_back if abs(e1.R_back) > 1e-12 else 0.0}")
        lines.append(f"  DISZ {e2.t_center}")
        lines.append(f"  GLAS {cand.glass2} 0 0 {e2.nd} {e2.vd}")
        lines.append("")

        # Surface 3: last surface
        lines.append("SURF 3")
        lines.append("  TYPE STANDARD")
        lines.append(f"  CURV {1.0 / e2.R_back if abs(e2.R_back) > 1e-12 else 0.0}")
        bfd = rx.back_focus_guess
        lines.append(f"  DISZ {bfd}")
        lines.append("")

        # Surface 4: Image
        lines.append("SURF 4")
        lines.append("  TYPE STANDARD")
        lines.append("  CURV 0.0")
        lines.append("  DISZ 0.0")
        lines.append("")

    else:
        # Surface 2: back of element 1
        lines.append("SURF 2")
        lines.append("  TYPE STANDARD")
        lines.append(f"  CURV {1.0 / e1.R_back if abs(e1.R_back) > 1e-12 else 0.0}")
        air_gap = rx.air_gap if rx.air_gap is not None else inputs.air_gap
        lines.append(f"  DISZ {air_gap}")
        lines.append("")

        # Surface 3: front of element 2
        lines.append("SURF 3")
        lines.append("  TYPE STANDARD")
        lines.append(f"  CURV {1.0 / e2.R_front if abs(e2.R_front) > 1e-12 else 0.0}")
        lines.append(f"  DISZ {e2.t_center}")
        lines.append(f"  GLAS {cand.glass2} 0 0 {e2.nd} {e2.vd}")
        lines.append("")

        # Surface 4: back of element 2
        lines.append("SURF 4")
        lines.append("  TYPE STANDARD")
        lines.append(f"  CURV {1.0 / e2.R_back if abs(e2.R_back) > 1e-12 else 0.0}")
        bfd = rx.back_focus_guess
        lines.append(f"  DISZ {bfd}")
        lines.append("")

        # Surface 5: Image
        lines.append("SURF 5")
        lines.append("  TYPE STANDARD")
        lines.append("  CURV 0.0")
        lines.append("  DISZ 0.0")
        lines.append("")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
